name: Check site for dead links
on: [push]
jobs:
  check-dead-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # - run: sudo apt update
      # - run: sudo apt install ruby-full build-essential zlib1g-dev
      # - run: sudo gem install jekyll bundler
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Verify no dead links
        run: |
          bundle exec rake test_gh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
