name: Check site for dead links
on: [push]
jobs:
  check-dead-links:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install ruby-full build-essential zlib1g-dev
      - run: sudo gem install jekyll bundler
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Verify no dead links
        run: |
          bundle install
          bundle exec rake test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
